// ============================================================
// PUZZLES - Exercise Definitions
// Based on Eloquent JavaScript exercises and concepts
// ============================================================

export const puzzleTypes = {
  predictOutput: {
    id: 'predict-output',
    title: 'Predict the Output',
    description: 'What will this code print?',
    icon: 'eye',
  },
  fixBug: {
    id: 'fix-bug',
    title: 'Fix the Bug',
    description: 'Find and fix the error in this code',
    icon: 'bug',
  },
  fillBlank: {
    id: 'fill-blank',
    title: 'Fill the Blank',
    description: 'Complete the missing code',
    icon: 'code',
  },
};

export const puzzles = {
  'values-types': [
    {
      id: 'p-vt-1',
      type: 'predict-output',
      title: 'Type Coercion',
      code: `console.log("5" - 1);\nconsole.log("5" + 1);\nconsole.log("five" * 2);`,
      expected: ['4', '51', 'NaN'],
      explanation: 'Subtraction converts "5" to 5 (result: 4). Addition converts 1 to "1" (result: "51"). Multiplication can\'t convert "five" to a number (result: NaN).',
      xp: 15,
      hints: ['Think about how JavaScript handles different types with each operator'],
    },
    {
      id: 'p-vt-2',
      type: 'predict-output',
      title: 'NaN Behavior',
      code: `console.log(NaN == NaN);\nconsole.log(isNaN(NaN));\nconsole.log(typeof NaN);`,
      expected: ['false', 'true', 'number'],
      explanation: 'NaN is not equal to itself (it\'s the only value with this property). isNaN() checks for NaN. typeof NaN returns "number" — NaN is technically a number value.',
      xp: 15,
      hints: ['NaN stands for "Not a Number" but it IS a number type'],
    },
    {
      id: 'p-vt-3',
      type: 'fill-blank',
      title: 'String Concatenation',
      code: `let greeting = "Hello" + "___" + "World";\nconsole.log(greeting); // → Hello World`,
      blanks: [' ', '  ', '_'],
      correct: ' ',
      explanation: 'Adding a space between words uses string concatenation with a space character.',
      xp: 10,
      hints: ['What character separates words in English?'],
    },
    {
      id: 'p-vt-4',
      type: 'predict-output',
      title: 'Falsy Values',
      code: `console.log(Boolean(0));\nconsole.log(Boolean(""));\nconsole.log(Boolean(null));\nconsole.log(Boolean(undefined));\nconsole.log(Boolean("0"));`,
      expected: ['false', 'false', 'false', 'false', 'true'],
      explanation: '0, "", null, and undefined are falsy. But "0" is a non-empty string, so it\'s truthy. Only 6 falsy values exist in JS.',
      xp: 20,
      hints: ['Empty strings and zero are falsy, but strings containing zero are truthy'],
    },
    {
      id: 'p-vt-5',
      type: 'fix-bug',
      title: 'String Comparison',
      code: `console.log("apple" < "banana");\nconsole.log("Zebra" < "apple");\nconsole.log("10" < "9");`,
      bugLine: 2,
      solution: 'console.log("Zebra".toLowerCase() < "apple".toLowerCase());',
      acceptableSolutions: [
        'console.log("zebra" < "apple");',
        'console.log("Zebra".toLowerCase() < "apple".toLowerCase());',
        'console.log("Zebra" < "apple");',
      ],
      explanation: 'String comparison is case-sensitive and based on Unicode values. Uppercase letters come before lowercase. "Z" (90) is less than "a" (97) in Unicode.',
      xp: 15,
      hints: ['Think about how uppercase and lowercase letters are ordered in Unicode'],
    },
  ],

  'program-structure': [
    {
      id: 'p-ps-1',
      type: 'predict-output',
      title: 'Loop Behavior',
      code: `let result = 0;\nfor (let i = 0; i < 5; i++) {\n  result += i;\n}\nconsole.log(result);`,
      expected: ['10'],
      explanation: 'The loop adds 0+1+2+3+4 = 10.',
      xp: 10,
      hints: ['Add up all values of i from 0 to 4'],
    },
    {
      id: 'p-ps-2',
      type: 'predict-output',
      title: 'Block Scope',
      code: `let x = 10;\nif (true) {\n  let x = 20;\n  console.log(x);\n}\nconsole.log(x);`,
      expected: ['20', '10'],
      explanation: 'let is block-scoped. Inside the if block, x is 20. Outside, x is still 10.',
      xp: 15,
      hints: ['let creates block-scoped variables'],
    },
    {
      id: 'p-ps-3',
      type: 'predict-output',
      title: 'While Loop',
      code: `let n = 0;\nwhile (n < 10) {\n  n = n * 2 + 1;\n}\nconsole.log(n);`,
      expected: ['15'],
      explanation: 'n goes: 0 → 1 → 3 → 7 → 15. At 15, the condition 15 < 10 is false.',
      xp: 15,
      hints: ['Trace through each iteration carefully'],
    },
    {
      id: 'p-ps-4',
      type: 'fill-blank',
      title: 'Loop Keyword',
      code: `___ (let i = 0; i < 10; i++) {\n  console.log(i);\n}`,
      blanks: ['for', 'while', 'do'],
      correct: 'for',
      explanation: 'The for loop is the standard way to count iterations with a known range.',
      xp: 10,
      hints: ['Which loop has initialization, condition, and update in one line?'],
    },
  ],

  'function-basics': [
    {
      id: 'p-fb-1',
      type: 'predict-output',
      title: 'Function Return',
      code: `function square(x) {\n  return x * x;\n}\nconst result = square(5) + square(3);\nconsole.log(result);`,
      expected: ['34'],
      explanation: 'square(5) = 25, square(3) = 9. 25 + 9 = 34.',
      xp: 10,
      hints: ['Call each function, then add the results'],
    },
    {
      id: 'p-fb-2',
      type: 'predict-output',
      title: 'Undefined Return',
      code: `function greet(name) {\n  console.log("Hi, " + name);\n}\nconst result = greet("Alice");\nconsole.log(result);`,
      expected: ['Hi, Alice', 'undefined'],
      explanation: 'greet prints "Hi, Alice" then returns undefined (no return statement).',
      xp: 15,
      hints: ['What does a function return when there is no return statement?'],
    },
    {
      id: 'p-fb-3',
      type: 'fix-bug',
      title: 'Missing Brace',
      code: `function add(a, b)\n  return a + b;\n}\nconsole.log(add(3, 4));`,
      bugLine: 1,
      solution: 'function add(a, b) {',
      acceptableSolutions: [
        'function add(a, b) {',
        'function add(a,b) {',
      ],
      explanation: 'The opening curly brace { is missing after the function parameters.',
      xp: 15,
      hints: ['Check the syntax around the function declaration'],
    },
    {
      id: 'p-fb-4',
      type: 'fill-blank',
      title: 'Return Statement',
      code: `function multiply(a, b) {\n  ___ a * b;\n}`,
      blanks: ['return', 'yield', 'output'],
      correct: 'return',
      explanation: 'The return keyword sends a value back from the function.',
      xp: 10,
      hints: ['Which keyword sends a value back from a function?'],
    },
    {
      id: 'p-fb-5',
      type: 'predict-output',
      title: 'Nested Calls',
      code: `function double(x) { return x * 2; }\nfunction addOne(x) { return x + 1; }\n\nconsole.log(addOne(double(5)));`,
      expected: ['11'],
      explanation: 'double(5) = 10, then addOne(10) = 11.',
      xp: 15,
      hints: ['Evaluate the innermost function call first'],
    },
  ],

  'higher-order-functions': [
    {
      id: 'p-hof-1',
      type: 'predict-output',
      title: 'Map Transform',
      code: `const nums = [1, 2, 3, 4];\nconst doubled = nums.map(n => n * 2);\nconsole.log(doubled);`,
      expected: ['[2, 4, 6, 8]'],
      explanation: 'map transforms each element: [1*2, 2*2, 3*2, 4*2] = [2, 4, 6, 8].',
      xp: 15,
      hints: ['map applies a function to every element'],
    },
    {
      id: 'p-hof-2',
      type: 'predict-output',
      title: 'Filter Selection',
      code: `const words = ["hi", "hey", "hello", "howdy"];\nconst longWords = words.filter(w => w.length > 3);\nconsole.log(longWords.length);`,
      expected: ['2'],
      explanation: '"hello" and "howdy" have more than 3 characters. That\'s 2 words.',
      xp: 15,
      hints: ['filter keeps elements where the function returns true'],
    },
    {
      id: 'p-hof-3',
      type: 'predict-output',
      title: 'Reduce Accumulation',
      code: `const nums = [10, 20, 30, 40];\nconst sum = nums.reduce((acc, n) => acc + n, 0);\nconsole.log(sum);`,
      expected: ['100'],
      explanation: 'reduce accumulates: 0+10=10, 10+20=30, 30+30=60, 60+40=100.',
      xp: 20,
      hints: ['reduce starts with initial value 0 and adds each number'],
    },
    {
      id: 'p-hof-4',
      type: 'fill-blank',
      title: 'Chain Method',
      code: `const result = [1, 2, 3, 4, 5]\n  .___(n => n % 2 === 0)\n  .map(n => n * 10);\n// result: [20, 40]`,
      blanks: ['filter', 'map', 'reduce'],
      correct: 'filter',
      explanation: 'filter keeps even numbers [2, 4], then map multiplies by 10.',
      xp: 15,
      hints: ['Which method selects a subset of elements?'],
    },
    {
      id: 'p-hof-5',
      type: 'predict-output',
      title: 'Chained Operations',
      code: `const items = [\n  { name: "apple", price: 1.50 },\n  { name: "banana", price: 0.75 },\n  { name: "cherry", price: 3.00 }\n];\nconst total = items\n  .filter(i => i.price > 1)\n  .map(i => i.price)\n  .reduce((sum, p) => sum + p, 0);\nconsole.log(total);`,
      expected: ['4.5'],
      explanation: 'Filter keeps apple (1.50) and cherry (3.00). Sum = 4.50.',
      xp: 20,
      hints: ['First filter by price, then sum the remaining prices'],
    },
  ],

  'arrays-basics': [
    {
      id: 'p-arr-1',
      type: 'predict-output',
      title: 'Array Index',
      code: `const arr = ["a", "b", "c", "d"];\nconsole.log(arr[1]);\nconsole.log(arr.length);`,
      expected: ['b', '4'],
      explanation: 'Arrays are zero-indexed: arr[1] is "b". Length is 4 (total elements).',
      xp: 10,
      hints: ['Array indices start at 0'],
    },
    {
      id: 'p-arr-2',
      type: 'predict-output',
      title: 'Push and Pop',
      code: `const stack = [1, 2, 3];\nstack.push(4);\nstack.pop();\nstack.push(5);\nconsole.log(stack);`,
      expected: ['[1, 2, 3, 5]'],
      explanation: 'push(4) adds 4: [1,2,3,4]. pop() removes 4: [1,2,3]. push(5) adds 5: [1,2,3,5].',
      xp: 15,
      hints: ['push adds to end, pop removes from end'],
    },
    {
      id: 'p-arr-3',
      type: 'fix-bug',
      title: 'Splice Mistake',
      code: `const arr = ["a", "b", "c"];\narr.splice(1, 0, "x");\nconsole.log(arr);`,
      bugLine: 2,
      solution: 'arr.splice(1, 1, "x");',
      acceptableSolutions: [
        'arr.splice(1, 1, "x");',
        'arr.splice(1,1,"x");',
      ],
      explanation: 'splice(index, deleteCount, ...items). deleteCount=0 removes nothing, so "x" is inserted without removing "b". deleteCount=1 removes "b".',
      xp: 15,
      hints: ['splice takes (start, deleteCount, ...items) — what should deleteCount be?'],
    },
    {
      id: 'p-arr-4',
      type: 'fill-blank',
      title: 'Array Spread',
      code: `const a = [1, 2];\nconst b = [3, 4];\nconst c = [...a, ...___, 5];\n// c: [1, 2, 3, 4, 5]`,
      blanks: ['b', 'a', 'c'],
      correct: 'b',
      explanation: 'Spread operator ... expands array elements. [...a, ...b, 5] combines all.',
      xp: 10,
      hints: ['Which array contains 3 and 4?'],
    },
  ],

  'spread-rest': [
    {
      id: 'p-sr-1',
      type: 'predict-output',
      title: 'Spread Merge',
      code: `const front = [1, 2];\nconst back = [3, 4];\nconst merged = [...front, ...back];\nconsole.log(merged);`,
      expected: ['[1, 2, 3, 4]'],
      explanation: 'Spread expands each array into individual elements: [1, 2, 3, 4].',
      xp: 10,
      hints: ['... spreads array elements into a new array'],
    },
    {
      id: 'p-sr-2',
      type: 'predict-output',
      title: 'Rest Parameters',
      code: `function sum(...nums) {\n  return nums.reduce((a, b) => a + b, 0);\n}\nconsole.log(sum(1, 2, 3, 4));`,
      expected: ['10'],
      explanation: 'rest collects all arguments into an array [1,2,3,4]. reduce sums them: 10.',
      xp: 15,
      hints: ['...rest collects arguments into an array'],
    },
    {
      id: 'p-sr-3',
      type: 'predict-output',
      title: 'Object Spread Override',
      code: `const defaults = { color: "blue", size: "md" };\nconst custom = { color: "red" };\nconst result = { ...defaults, ...custom };\nconsole.log(result);`,
      expected: ['{ color: "red", size: "md" }'],
      explanation: 'custom\'s "color: red" overrides defaults\' "color: blue". size stays "md".',
      xp: 20,
      hints: ['Later properties override earlier ones in spread'],
    },
    {
      id: 'p-sr-4',
      type: 'fill-blank',
      title: 'Destructuring Rest',
      code: `const [first, ...rest] = [10, 20, 30, 40];\nconsole.log(rest); // → [___]`,
      blanks: ['20, 30, 40', '10, 20, 30', '30, 40'],
      correct: '20, 30, 40',
      explanation: 'first gets 10, rest collects the remaining [20, 30, 40].',
      xp: 15,
      hints: ['rest collects everything except the first element'],
    },
  ],

  'object-basics': [
    {
      id: 'p-obj-1',
      type: 'predict-output',
      title: 'Property Access',
      code: `const user = { name: "Alice", age: 30 };\nconsole.log(user.name);\nconsole.log(user["age"]);`,
      expected: ['Alice', '30'],
      explanation: 'Dot notation and bracket notation both access properties. Bracket takes a string.',
      xp: 10,
      hints: ['Both notations access the same property'],
    },
    {
      id: 'p-obj-2',
      type: 'predict-output',
      title: 'Computed Property',
      code: `const key = "score";\nconst obj = { [key]: 100 };\nconsole.log(obj.score);`,
      expected: ['100'],
      explanation: 'Computed property [key] uses the value of key as the property name.',
      xp: 15,
      hints: ['[key] means "use the variable key\'s value as the property name"'],
    },
    {
      id: 'p-obj-3',
      type: 'predict-output',
      title: 'Object Reference',
      code: `const a = { x: 1 };\nconst b = a;\nb.x = 2;\nconsole.log(a.x);`,
      expected: ['2'],
      explanation: 'Objects are assigned by reference. b points to the same object as a, so changing b.x changes a.x.',
      xp: 20,
      hints: ['Objects are not copied — they are referenced'],
    },
    {
      id: 'p-obj-4',
      type: 'fix-bug',
      title: 'Method This',
      code: `const obj = {\n  name: "Alice",\n  greet() {\n    console.log("Hello, " + this.name);\n  }\n};\nconst fn = obj.greet;\nfn();`,
      bugLine: 5,
      solution: 'const fn = obj.greet.bind(obj);',
      acceptableSolutions: [
        'const fn = obj.greet.bind(obj);',
        'fn.call(obj);',
        'fn.apply(obj);',
      ],
      explanation: 'When greet is called as fn(), this is undefined (or window). bind(obj) ensures this refers to obj.',
      xp: 20,
      hints: ['How do you preserve the context of a method when extracting it?'],
    },
  ],

  'destructuring-spread': [
    {
      id: 'p-ds-1',
      type: 'predict-output',
      title: 'Object Destructuring',
      code: `const { name, age = 25 } = { name: "Alice" };\nconsole.log(name, age);`,
      expected: ['Alice 25'],
      explanation: 'name extracts "Alice". age is missing, so the default value 25 is used.',
      xp: 15,
      hints: ['Default values apply when a property is missing'],
    },
    {
      id: 'p-ds-2',
      type: 'predict-output',
      title: 'Nested Destructuring',
      code: `const user = {\n  address: { city: "NYC", zip: "10001" }\n};\nconst { address: { city } } = user;\nconsole.log(city);`,
      expected: ['NYC'],
      explanation: 'Nested destructuring extracts city from user.address.city.',
      xp: 20,
      hints: ['Match the nesting structure of the object'],
    },
    {
      id: 'p-ds-3',
      type: 'fill-blank',
      title: 'Array Swap',
      code: `let a = 1, b = 2;\n[___, b] = [b, a];\nconsole.log(a, b); // → 2 1`,
      blanks: ['a', 'b', 'temp'],
      correct: 'a',
      explanation: 'Destructuring swap: [a, b] = [b, a] swaps the values without a temp variable.',
      xp: 15,
      hints: ['Which variable should get the new value first?'],
    },
    {
      id: 'p-ds-4',
      type: 'predict-output',
      title: 'Rename Destructuring',
      code: `const { name: userName, age: userAge } = { name: "Bob", age: 25 };\nconsole.log(userName);`,
      expected: ['Bob'],
      explanation: 'name: userName renames the extracted property to userName.',
      xp: 15,
      hints: ['The colon in destructuring renames the variable'],
    },
  ],

  'dom-intro': [
    {
      id: 'p-dom-1',
      type: 'predict-output',
      title: 'DOM Selection',
      code: `// Assuming: <div id="box">Hello</div>\nconst el = document.getElementById("box");\nconsole.log(el.textContent);`,
      expected: ['Hello'],
      explanation: 'getElementById finds the element, textContent returns its text content.',
      xp: 10,
      hints: ['textContent returns the text inside an element'],
    },
    {
      id: 'p-dom-2',
      type: 'predict-output',
      title: 'Node Types',
      code: `const div = document.createElement("div");\nconst text = document.createTextNode("hi");\nconsole.log(div.nodeType);\nconsole.log(text.nodeType);`,
      expected: ['1', '3'],
      explanation: 'Element nodes have nodeType 1, Text nodes have nodeType 3.',
      xp: 15,
      hints: ['Elements are type 1, text is type 3'],
    },
  ],

  'selecting-elements': [
    {
      id: 'p-sel-1',
      type: 'fill-blank',
      title: 'Query Selector',
      code: `const el = document.___(".card .title");`,
      blanks: ['querySelector', 'getElementById', 'querySelectorAll'],
      correct: 'querySelector',
      explanation: 'querySelector finds the first element matching a CSS selector.',
      xp: 10,
      hints: ['Which method uses CSS selectors to find elements?'],
    },
    {
      id: 'p-sel-2',
      type: 'predict-output',
      title: 'querySelectorAll Count',
      code: `// Assuming: <ul><li>A</li><li>B</li><li>C</li></ul>\nconst items = document.querySelectorAll("li");\nconsole.log(items.length);`,
      expected: ['3'],
      explanation: 'querySelectorAll returns all matching elements as a NodeList.',
      xp: 10,
      hints: ['How many <li> elements are there?'],
    },
  ],

  'manipulating-dom': [
    {
      id: 'p-dom-1',
      type: 'predict-output',
      title: 'textContent vs innerHTML',
      code: `const div = document.createElement("div");\ndiv.textContent = "<b>Hello</b>";\nconsole.log(div.innerHTML);`,
      expected: ['&lt;b&gt;Hello&lt;/b&gt;'],
      explanation: 'textContent escapes HTML. innerHTML shows the escaped version because textContent doesn\'t parse HTML.',
      xp: 15,
      hints: ['textContent treats content as plain text, not HTML'],
    },
    {
      id: 'p-dom-2',
      type: 'predict-output',
      title: 'ClassList Toggle',
      code: `const div = document.createElement("div");\ndiv.classList.add("active");\ndiv.classList.toggle("active");\ndiv.classList.toggle("active");\nconsole.log(div.classList.contains("active"));`,
      expected: ['true'],
      explanation: 'add makes it active. toggle removes it (now inactive). toggle adds it (now active). contains returns true.',
      xp: 15,
      hints: ['toggle removes if present, adds if absent'],
    },
  ],

  'event-basics': [
    {
      id: 'p-evt-1',
      type: 'fill-blank',
      title: 'Event Listener',
      code: `button.addEventListener("___", function() {\n  console.log("Clicked!");\n});`,
      blanks: ['click', 'hover', 'press'],
      correct: 'click',
      explanation: '"click" is the most common event for button interactions.',
      xp: 10,
      hints: ['What event fires when a user clicks a button?'],
    },
    {
      id: 'p-evt-2',
      type: 'predict-output',
      title: 'Multiple Listeners',
      code: `const btn = document.createElement("button");\nbtn.addEventListener("click", () => console.log("A"));\nbtn.addEventListener("click", () => console.log("B"));\nbtn.click();`,
      expected: ['A', 'B'],
      explanation: 'Multiple listeners on the same event all fire in registration order.',
      xp: 15,
      hints: ['Each addEventListener adds a handler — they don\'t replace each other'],
    },
  ],

  'event-object': [
    {
      id: 'p-eo-1',
      type: 'predict-output',
      title: 'preventDefault',
      code: `const form = document.createElement("form");\nform.addEventListener("submit", (e) => {\n  e.preventDefault();\n  console.log("Blocked!");\n});\n// Form submission is prevented`,
      expected: ['Blocked!'],
      explanation: 'preventDefault() stops the browser\'s default behavior (page reload for forms).',
      xp: 15,
      hints: ['preventDefault stops the default browser action'],
    },
    {
      id: 'p-eo-2',
      type: 'predict-output',
      title: 'Event Target',
      code: `const parent = document.createElement("div");\nconst child = document.createElement("button");\nparent.appendChild(child);\nparent.addEventListener("click", (e) => {\n  console.log(e.target === child);\n});\nchild.click();`,
      expected: ['true'],
      explanation: 'e.target is the element that was actually clicked (child), not the handler element (parent).',
      xp: 15,
      hints: ['target is what triggered the event, currentTarget is the handler element'],
    },
  ],

  'event-delegation': [
    {
      id: 'p-ed-1',
      type: 'predict-output',
      title: 'Event Bubbling',
      code: `const grandparent = document.createElement("div");\nconst parent = document.createElement("div");\nconst child = document.createElement("button");\nparent.appendChild(child);\ngrandparent.appendChild(parent);\n\ngrandparent.addEventListener("click", () => console.log("GP"));\nparent.addEventListener("click", () => console.log("P"));\nchild.addEventListener("click", () => console.log("C"));\nchild.click();`,
      expected: ['C', 'P', 'GP'],
      explanation: 'Events bubble up: child → parent → grandparent.',
      xp: 15,
      hints: ['Events propagate from the target up through ancestors'],
    },
    {
      id: 'p-ed-2',
      type: 'fill-blank',
      title: 'Find Closest Ancestor',
      code: `const item = e.target.___(".card");`,
      blanks: ['closest', 'querySelector', 'parentElement'],
      correct: 'closest',
      explanation: 'closest() finds the nearest ancestor (including self) matching the selector.',
      xp: 15,
      hints: ['Which method searches up the DOM tree?'],
    },
  ],

  'callbacks-promises': [
    {
      id: 'p-cp-1',
      type: 'predict-output',
      title: 'Promise Resolution',
      code: `const p = new Promise((resolve) => {\n  resolve("done");\n});\np.then(v => console.log(v));`,
      expected: ['done'],
      explanation: 'resolve("done") makes the promise fulfill with "done", which .then() receives.',
      xp: 15,
      hints: ['resolve() passes a value to the next .then()'],
    },
    {
      id: 'p-cp-2',
      type: 'predict-output',
      title: 'Promise Chain',
      code: `Promise.resolve(1)\n  .then(x => x + 1)\n  .then(x => x * 2)\n  .then(x => console.log(x));`,
      expected: ['4'],
      explanation: '1→2 (add 1) → 4 (multiply by 2). Each .then() transforms the value.',
      xp: 20,
      hints: ['Each then() returns a new promise with the transformed value'],
    },
    {
      id: 'p-cp-3',
      type: 'predict-output',
      title: 'Promise.all',
      code: `const p1 = Promise.resolve(1);\nconst p2 = Promise.resolve(2);\nconst p3 = Promise.resolve(3);\nPromise.all([p1, p2, p3]).then(r => console.log(r));`,
      expected: ['[1, 2, 3]'],
      explanation: 'Promise.all resolves with an array of all resolved values.',
      xp: 20,
      hints: ['Promise.all collects all results into an array'],
    },
  ],

  'async-await': [
    {
      id: 'p-aa-1',
      type: 'predict-output',
      title: 'Async Function',
      code: `async function getData() {\n  return 42;\n}\ngetData().then(v => console.log(v));`,
      expected: ['42'],
      explanation: 'async functions always return a Promise. return 42 becomes Promise.resolve(42).',
      xp: 15,
      hints: ['async functions wrap return values in a Promise'],
    },
    {
      id: 'p-aa-2',
      type: 'predict-output',
      title: 'Await Behavior',
      code: `async function run() {\n  const a = await Promise.resolve(10);\n  const b = await Promise.resolve(20);\n  console.log(a + b);\n}\nrun();`,
      expected: ['30'],
      explanation: 'await unwraps the Promise. a=10, b=20, sum=30.',
      xp: 15,
      hints: ['await pauses until the Promise resolves, then returns its value'],
    },
    {
      id: 'p-aa-3',
      type: 'predict-output',
      title: 'Parallel Async',
      code: `async function run() {\n  const [a, b] = await Promise.all([\n    Promise.resolve(10),\n    Promise.resolve(20)\n  ]);\n  console.log(a + b);\n}\nrun();`,
      expected: ['30'],
      explanation: 'Promise.all runs both in parallel. a=10, b=20, sum=30.',
      xp: 20,
      hints: ['Promise.all waits for all promises simultaneously'],
    },
  ],

  'canvas-basics': [
    {
      id: 'p-cb-1',
      type: 'predict-output',
      title: 'Canvas Arc',
      code: `// Full circle: 0 to Math.PI * 2\n// Quarter circle: 0 to Math.PI / 2\nconsole.log(Math.PI * 2);`,
      expected: ['6.283185307179586'],
      explanation: 'A full circle is 2π radians (approximately 6.28).',
      xp: 10,
      hints: ['2 * Math.PI gives a full circle in radians'],
    },
    {
      id: 'p-cb-2',
      type: 'fill-blank',
      title: 'Canvas Context',
      code: `const canvas = document.querySelector("canvas");\nconst cx = canvas.___("2d");`,
      blanks: ['getContext', 'getContext2D', 'createContext'],
      correct: 'getContext',
      explanation: 'getContext("2d") returns the 2D drawing context for a canvas.',
      xp: 10,
      hints: ['Which method gets the drawing interface from a canvas?'],
    },
  ],

  'fetch-api': [
    {
      id: 'p-fetch-1',
      type: 'predict-output',
      title: 'Fetch Response',
      code: `const response = new Response("Hello", {\n  status: 200,\n  headers: { "Content-Type": "text/plain" }\n});\nconsole.log(response.ok);`,
      expected: ['true'],
      explanation: 'Status 200 is in the 200-299 range, so response.ok is true.',
      xp: 15,
      hints: ['ok is true when status is between 200 and 299'],
    },
    {
      id: 'p-fetch-2',
      type: 'fill-blank',
      title: 'JSON Body',
      code: `await fetch("/api", {\n  method: "POST",\n  headers: { "Content-Type": "application/json" },\n  body: ___({ name: "Alice" })\n});`,
      blanks: ['JSON.stringify', 'JSON.parse', 'String'],
      correct: 'JSON.stringify',
      explanation: 'fetch requires the body to be a string when sending JSON. JSON.stringify converts an object to a JSON string.',
      xp: 15,
      hints: ['Convert the object to a JSON string before sending'],
    },
  ],

  'node-intro': [
    {
      id: 'p-node-1',
      type: 'predict-output',
      title: 'Process Args',
      code: `// Run: node script.js hello world\nconsole.log(process.argv.length);`,
      expected: ['4'],
      explanation: 'process.argv has: ["node", "script.js", "hello", "world"] — length 4.',
      xp: 10,
      hints: ['process.argv includes node and the script name'],
    },
    {
      id: 'p-node-2',
      type: 'fill-blank',
      title: 'Import Syntax',
      code: `___ { readFile } from "node:fs/promises";`,
      blanks: ['import', 'require', 'include'],
      correct: 'import',
      explanation: 'ES modules use import/export. CommonJS uses require().',
      xp: 10,
      hints: ['Which keyword is used in ES modules to bring in functionality?'],
    },
  ],

  'http-server': [
    {
      id: 'p-http-1',
      type: 'predict-output',
      title: 'HTTP Status',
      code: `// If a server returns:\n// HTTP/1.1 404 Not Found\n// What does 404 mean?`,
      expected: ['Not Found', 'not found', '404'],
      explanation: '404 means the requested resource could not be found on the server.',
      xp: 10,
      hints: ['4xx status codes indicate client errors'],
    },
    {
      id: 'p-http-2',
      type: 'fill-blank',
      title: 'HTTP Methods',
      code: `// Use ___ to create a new resource\n// Use ___ to read a resource\n// Use ___ to delete a resource`,
      blanks: ['PUT, GET, DELETE', 'POST, GET, DELETE', 'CREATE, READ, DELETE'],
      correct: 'PUT, GET, DELETE',
      explanation: 'REST conventions: PUT creates/replaces, GET reads, DELETE removes. POST is also used for creation.',
      xp: 15,
      hints: ['Think about CRUD operations: Create, Read, Update, Delete'],
    },
  ],

  'selecting-elements': [
    {
      id: 'p-sel-1',
      type: 'fill-blank',
      title: 'Query Selector',
      code: `const el = document.___(".card .title");`,
      blanks: ['querySelector', 'getElementById', 'querySelectorAll'],
      correct: 'querySelector',
      explanation: 'querySelector finds the first element matching a CSS selector.',
      xp: 10,
      hints: ['Which method uses CSS selectors to find elements?'],
    },
    {
      id: 'p-sel-2',
      type: 'predict-output',
      title: 'querySelectorAll Count',
      code: `// Assuming: <ul><li>A</li><li>B</li><li>C</li></ul>\nconst items = document.querySelectorAll("li");\nconsole.log(items.length);`,
      expected: ['3'],
      explanation: 'querySelectorAll returns all matching elements as a NodeList.',
      xp: 10,
      hints: ['How many <li> elements are there?'],
    },
  ],

  'manipulating-dom': [
    {
      id: 'p-md-1',
      type: 'predict-output',
      title: 'textContent vs innerHTML',
      code: `const div = document.createElement("div");\ndiv.textContent = "<b>Hello</b>";\nconsole.log(div.innerHTML);`,
      expected: ['&lt;b&gt;Hello&lt;/b&gt;'],
      explanation: 'textContent escapes HTML tags and shows them as plain text.',
      xp: 15,
      hints: ['textContent treats content as plain text, not HTML'],
    },
    {
      id: 'p-md-2',
      type: 'predict-output',
      title: 'ClassList Toggle',
      code: `const div = document.createElement("div");\ndiv.classList.add("active");\ndiv.classList.toggle("active");\ndiv.classList.toggle("active");\nconsole.log(div.classList.contains("active"));`,
      expected: ['true'],
      explanation: 'add makes it active. toggle removes it. toggle adds it again. contains returns true.',
      xp: 15,
      hints: ['toggle removes if present, adds if absent'],
    },
  ],

  'event-object': [
    {
      id: 'p-eo-1',
      type: 'predict-output',
      title: 'preventDefault',
      code: `const form = document.createElement("form");\nlet submitted = false;\nform.addEventListener("submit", (e) => {\n  e.preventDefault();\n  submitted = true;\n});\nform.dispatchEvent(new Event("submit"));\nconsole.log(submitted);`,
      expected: ['true'],
      explanation: 'preventDefault stops page reload but the handler still runs and sets submitted to true.',
      xp: 15,
      hints: ['preventDefault stops the default action but not the handler'],
    },
  ],

  'event-delegation': [
    {
      id: 'p-ed-1',
      type: 'predict-output',
      title: 'Event Bubbling',
      code: `const grandparent = document.createElement("div");\nconst parent = document.createElement("div");\nconst child = document.createElement("button");\nparent.appendChild(child);\ngrandparent.appendChild(parent);\n\nlet log = [];\ngrandparent.addEventListener("click", () => log.push("GP"));\nparent.addEventListener("click", () => log.push("P"));\nchild.addEventListener("click", () => log.push("C"));\nchild.click();\nconsole.log(log.join(", "));`,
      expected: ['C, P, GP'],
      explanation: 'Events bubble up: child fires first, then parent, then grandparent.',
      xp: 15,
      hints: ['Events propagate from the target up through ancestors'],
    },
  ],

  'callbacks-promises': [
    {
      id: 'p-cp-1',
      type: 'predict-output',
      title: 'Promise Resolution',
      code: `const p = new Promise((resolve) => {\n  resolve("done");\n});\np.then(v => console.log(v));`,
      expected: ['done'],
      explanation: 'resolve("done") makes the promise fulfill with "done", which .then() receives.',
      xp: 15,
      hints: ['resolve() passes a value to the next .then()'],
    },
    {
      id: 'p-cp-2',
      type: 'predict-output',
      title: 'Promise Chain',
      code: `Promise.resolve(1)\n  .then(x => x + 1)\n  .then(x => x * 2)\n  .then(x => console.log(x));`,
      expected: ['4'],
      explanation: '1→2 (add 1) → 4 (multiply by 2). Each .then() transforms the value.',
      xp: 20,
      hints: ['Each then() returns a new promise with the transformed value'],
    },
  ],

  'async-await': [
    {
      id: 'p-aa-1',
      type: 'predict-output',
      title: 'Async Function',
      code: `async function getData() {\n  return 42;\n}\ngetData().then(v => console.log(v));`,
      expected: ['42'],
      explanation: 'async functions always return a Promise. return 42 becomes Promise.resolve(42).',
      xp: 15,
      hints: ['async functions wrap return values in a Promise'],
    },
    {
      id: 'p-aa-2',
      type: 'predict-output',
      title: 'Await Behavior',
      code: `async function run() {\n  const a = await Promise.resolve(10);\n  const b = await Promise.resolve(20);\n  console.log(a + b);\n}\nrun();`,
      expected: ['30'],
      explanation: 'await unwraps the Promise. a=10, b=20, sum=30.',
      xp: 15,
      hints: ['await pauses until the Promise resolves, then returns its value'],
    },
  ],

  'fetch-api': [
    {
      id: 'p-fa-1',
      type: 'predict-output',
      title: 'Fetch Response',
      code: `const response = new Response("Hello", {\n  status: 200,\n  headers: { "Content-Type": "text/plain" }\n});\nconsole.log(response.ok);`,
      expected: ['true'],
      explanation: 'Status 200 is in the 200-299 range, so response.ok is true.',
      xp: 15,
      hints: ['ok is true when status is between 200 and 299'],
    },
    {
      id: 'p-fa-2',
      type: 'fill-blank',
      title: 'JSON Body',
      code: `await fetch("/api", {\n  method: "POST",\n  headers: { "Content-Type": "application/json" },\n  body: ___({ name: "Alice" })\n});`,
      blanks: ['JSON.stringify', 'JSON.parse', 'String'],
      correct: 'JSON.stringify',
      explanation: 'fetch requires the body to be a string when sending JSON.',
      xp: 15,
      hints: ['Convert the object to a JSON string before sending'],
    },
  ],

  'canvas-basics': [
    {
      id: 'p-cb-1',
      type: 'fill-blank',
      title: 'Canvas Context',
      code: `const canvas = document.querySelector("canvas");\nconst cx = canvas.___("2d");`,
      blanks: ['getContext', 'getContext2D', 'createContext'],
      correct: 'getContext',
      explanation: 'getContext("2d") returns the 2D drawing context for a canvas.',
      xp: 10,
      hints: ['Which method gets the drawing interface from a canvas?'],
    },
  ],

  'file-system': [
    {
      id: 'p-fs-1',
      type: 'fill-blank',
      title: 'Read File',
      code: `import { ___ } from "node:fs/promises";\nconst text = await readFile("file.txt", "utf8");`,
      blanks: ['readFile', 'openFile', 'loadFile'],
      correct: 'readFile',
      explanation: 'readFile is the function for reading file contents in Node.js.',
      xp: 10,
      hints: ['What operation do you want to perform on the file?'],
    },
  ],
};

export function getPuzzlesForLesson(lessonId) {
  return puzzles[lessonId] || [];
}

export function validateAnswer(puzzle, userAnswer) {
  if (puzzle.type === 'predict-output') {
    const normalized = userAnswer.trim().toLowerCase();
    return puzzle.expected.some(e => normalized.includes(e.toLowerCase()));
  }

  if (puzzle.type === 'fix-bug') {
    const normalized = userAnswer.trim().toLowerCase();
    return puzzle.acceptableSolutions.some(s => normalized.includes(s.toLowerCase()));
  }

  if (puzzle.type === 'fill-blank') {
    return userAnswer.trim().toLowerCase() === puzzle.correct.toLowerCase();
  }

  return false;
}
